# Generated by Django 3.1.7 on 2021-03-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chp_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_name', models.CharField(max_length=6)),
                ('cls_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_name', models.CharField(max_length=50)),
                ('crs_start_datetime', models.DateTimeField()),
                ('crs_end_datetime', models.DateTimeField()),
                ('chp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.chapter')),
                ('crs_classroom', models.ManyToManyField(related_name='classroom_attributed', to='RV1.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcm_name', models.CharField(max_length=100)),
                ('dcm_subpath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dct_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl_name', models.CharField(max_length=50)),
                ('mdl_start_date', models.DateField()),
                ('mdl_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prt_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='usr_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usr_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='usr_firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='usr_gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usr_lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='usr_root_dir',
            field=models.CharField(default='/.tempRootDir', max_length=100),
        ),
        migrations.CreateModel(
            name='Share_Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.chapter')),
                ('crs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.course')),
                ('dcm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.document')),
                ('mdl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.module')),
            ],
        ),
        migrations.CreateModel(
            name='Share_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.document')),
                ('prt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.permission_type')),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_code', models.CharField(max_length=10)),
                ('grp_name', models.CharField(max_length=50)),
                ('grp_start_date', models.DateField()),
                ('grp_end_date', models.DateField()),
                ('grp_course', models.ManyToManyField(related_name='course_taken', to='RV1.Module')),
                ('grp_user', models.ManyToManyField(related_name='user_belonging', to='RV1.User')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='dct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.document_type'),
        ),
        migrations.AddField(
            model_name='document',
            name='usr_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='crs_teacher',
            field=models.ManyToManyField(related_name='teacher_participating', to='RV1.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='mdl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.module'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='mdl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RV1.module'),
        ),
    ]
