# Generated by Django 3.0.14 on 2021-06-03 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0002_auto_20210308_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_birth_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
