# Generated by Django 3.0.14 on 2021-06-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0003_user_usr_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='mdl_id',
        ),
        migrations.AddField(
            model_name='chapter',
            name='mdl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RV1.Module'),
            preserve_default=False,
        ),
    ]
