# Generated by Django 3.0.14 on 2021-06-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0004_auto_20210603_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='dct_id',
        ),
        migrations.AddField(
            model_name='document',
            name='dct',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='RV1.Document_Type'),
            preserve_default=False,
        ),
    ]
