# Generated by Django 3.0.14 on 2021-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0007_course_crs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chp_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
