# Generated by Django 3.0.14 on 2021-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0008_chapter_chp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='crs_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
