# Generated by Django 3.0.14 on 2021-06-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0009_course_crs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_gender',
            field=models.BooleanField(default=False),
        ),
    ]
