# Generated by Django 3.0.14 on 2021-06-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV1', '0010_auto_20210604_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_gender',
            field=models.BooleanField(default=True),
        ),
    ]
